#!/bin/bash

cd $HOME
git clone https://github.com/Raspberry-Pi-Reviews/Suda-Music
cd $HOME/Suda-Music
chmod +x musicplayer.py
echo "[Desktop Entry]
Name=Suda Music
Comment= Suda Music is a free to use music player.
Exec=python3 /home/pi/Suda-Music/musicplayer.py
Icon=/home/pi/Suda-Music/Images/music.png
Terminal=false
StartupNotify=true
Type=Application
Categories=Audio;Music;Player;AudioVideo;" > ~/.local/share/applications/Suda-Music.desktop || error "Failed to create menu button!"
