#!/bin/bash

git clone https://github.com/Raspberry-Pi-Reviews/Suda-Music
cd $HOME/Suda-Music
chmod +x musicplayer.py
chmod +x start
echo "[Desktop Entry]
Name=Suda Music
Comment= Suda Music is a free to use music player.
Exec=$DIRECTORY/etc/terminal-run $HOME/Suda-Music/start 'Suda Music'
Icon=$HOME/Suda-Music/Images/music.png
Terminal=true
StartupNotify=true
Type=Application
Categories=Utility;" > ~/.local/share/applications/Suda-Music.desktop || error "Failed to create menu button!""

